# environment.yml
name: rag-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pip:
    - fastapi==0.108.0
    - uvicorn==0.27.0
    - pydantic==2.5.3
    - pydantic-settings==2.1.0
    - pymongo==4.6.1
    - motor==3.3.2
    - python-dotenv==1.0.0
    - python-multipart==0.0.6
    - beautifulsoup4==4.12.2
    - requests==2.31.0
    - rich==13.7.0
    # LangChain dependencies with compatible versions
    - langchain>=0.1.0
    - langchain-openai>=0.0.5
    - langchain-community>=0.0.16
    - langchain-text-splitters>=0.0.1
    - langgraph>=0.0.20
    - faiss-cpu==1.7.4